import { BarChart3, Command, DatabaseZap, FolderTree, KeyRound, ReceiptText, ShieldCheck, Sprout, TrendingUp, WalletCards } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import AuthModal from '../components/auth/AuthModal.jsx';
import ThemeToggle from '../components/theme/ThemeToggle.jsx';
import { Badge } from '../components/ui/badge.jsx';
import { Button } from '../components/ui/button.jsx';
import { Card, CardContent } from '../components/ui/card.jsx';
import { useAuth } from '../context/AuthContext.jsx';
const features=[['Command search',Command,'Search records, categories, keys, and routes from one command surface.'],['Executive dashboard',BarChart3,'See cash flow, category pressure, and recent ledger movement instantly.'],['Custom taxonomy',FolderTree,'Model farm-specific income, expense, and metadata structures.'],['Developer access',KeyRound,'Manage MCP endpoint and client keys from a professional settings surface.']];
export default function LandingPage({ initialAuthMode = null }) {
  const { isAuthenticated } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [authMode,setAuthMode]=useState(initialAuthMode); useEffect(()=>setAuthMode(initialAuthMode),[initialAuthMode]); const destination=useMemo(()=>location.state?.from?.pathname||'/dashboard',[location.state]); const openAuth=(mode)=>{setAuthMode(mode);navigate(`/${mode}`,{replace:false,state:location.state});}; const closeAuth=()=>{setAuthMode(null);navigate('/',{replace:true});}; const openDashboard=()=>navigate('/dashboard');
  return <main className="min-h-screen bg-background text-foreground"><nav className="sticky top-0 z-40 border-b bg-background/85 backdrop-blur"><div className="mx-auto flex h-14 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><button className="flex items-center gap-2 text-[13px] font-semibold" type="button" onClick={()=>navigate('/')}><span className="flex h-8 w-8 items-center justify-center rounded-md border"><Sprout className="h-4 w-4 text-primary" /></span>Farm Accounts</button><div className="flex items-center gap-2"><ThemeToggle compact />{isAuthenticated?<Button type="button" onClick={openDashboard}>Open dashboard</Button>:<><Button variant="ghost" type="button" onClick={()=>openAuth('login')}>Login</Button><Button type="button" onClick={()=>openAuth('signup')}>Sign up</Button></>}</div></div></nav>
    <section className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[1fr_560px] lg:px-8 lg:py-20"><div className="flex flex-col justify-center"><Badge variant="outline" className="mb-5 w-fit">Modern farm finance SaaS</Badge><h1 className="max-w-3xl text-4xl font-semibold tracking-[-.02em] sm:text-5xl">A Vercel-grade command center for farm accounts.</h1><p className="mt-5 max-w-2xl text-[15px] leading-7 text-muted-foreground">Replace spreadsheet drift with a fast, searchable workspace for income, expenses, categories, reporting, and secure MCP access.</p><div className="mt-7 flex flex-wrap gap-2">{isAuthenticated?<Button size="lg" type="button" onClick={openDashboard}>Open dashboard</Button>:<><Button size="lg" type="button" onClick={()=>openAuth('signup')}>Start workspace</Button><Button size="lg" variant="outline" type="button" onClick={()=>openAuth('login')}>Login</Button></>}</div><div className="mt-8 grid max-w-lg grid-cols-3 gap-3 text-xs"><div><strong className="block text-foreground">Global</strong><span className="text-muted-foreground">Command search</span></div><div><strong className="block text-foreground">Live</strong><span className="text-muted-foreground">Ledger views</span></div><div><strong className="block text-foreground">Secure</strong><span className="text-muted-foreground">MCP access</span></div></div></div>
      <Card className="overflow-hidden bg-muted/10 shadow-2xl shadow-black/5"><div className="flex h-10 items-center gap-2 border-b px-3"><span className="h-2.5 w-2.5 rounded-full bg-red-500"/><span className="h-2.5 w-2.5 rounded-full bg-yellow-500"/><span className="h-2.5 w-2.5 rounded-full bg-green-500"/><div className="ml-auto rounded-md border px-2 py-1 font-mono text-[10px] text-muted-foreground">⌘K</div></div><CardContent className="grid gap-3 p-4"><div className="grid gap-3 sm:grid-cols-3"><PreviewMetric icon={WalletCards} label="Income" value="₹8.42L" tone="text-income"/><PreviewMetric icon={ReceiptText} label="Expense" value="₹3.18L" tone="text-expense"/><PreviewMetric icon={TrendingUp} label="Net" value="₹5.24L" tone="text-balance"/></div><div className="grid gap-3 lg:grid-cols-[1fr_190px]"><div className="flex h-56 items-end gap-2 rounded-lg border bg-background p-4">{[42,68,54,82,64,72,88,61].map((h,i)=><span className="flex-1 rounded-t-sm bg-foreground" style={{height:`${h}%`,opacity:.12+i*.06}} key={`${h}-${i}`}/>)}</div><div className="grid gap-2">{['Crop sale','Fertilizer','Irrigation','MCP key'].map((item,i)=><div className="rounded-md border bg-background p-2" key={item}><div className="text-xs font-medium">{item}</div><div className="text-[11px] text-muted-foreground">{i%2?'Expense':'Income'} · indexed</div></div>)}</div></div></CardContent></Card>
    </section><section className="border-y bg-muted/15"><div className="mx-auto grid max-w-7xl gap-3 px-4 py-10 sm:px-6 md:grid-cols-2 lg:grid-cols-4 lg:px-8">{features.map(([title,Icon,copy])=><div className="rounded-lg border bg-background p-4" key={title}><Icon className="mb-3 h-4 w-4 text-primary"/><h2 className="text-[13px] font-semibold">{title}</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">{copy}</p></div>)}</div></section><section className="mx-auto grid max-w-7xl gap-4 px-4 py-14 sm:px-6 lg:grid-cols-3 lg:px-8"><div className="lg:col-span-2"><h2 className="text-2xl font-semibold">Built for repeat finance work, not a brochure.</h2><p className="mt-3 text-sm text-muted-foreground">Dense ledgers, quick creation flows, audited developer access, and searchable records make the workspace feel like a real operating system for farm finance.</p></div><Card><CardContent className="p-4"><ShieldCheck className="mb-3 h-4 w-4 text-primary"/><h3 className="text-[13px] font-semibold">Governed access</h3><p className="mt-2 text-xs text-muted-foreground">Create and disable MCP keys so connected workflows stay controlled.</p></CardContent></Card></section><footer className="border-t"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-6 text-xs text-muted-foreground sm:px-6 lg:px-8"><span>Farm Accounts</span><span>Professional finance control for farm operations.</span></div></footer>{authMode&&<AuthModal mode={authMode} onClose={closeAuth} onModeChange={(nextMode)=>{setAuthMode(nextMode);navigate(`/${nextMode}`,{replace:true,state:location.state});}} onSuccess={()=>navigate(destination,{replace:true})}/>}</main>;
}
function PreviewMetric({ icon: Icon, label, value, tone }) { return <div className="rounded-lg border bg-background p-3"><Icon className={`mb-3 h-4 w-4 ${tone}`} /><p className="text-[11px] text-muted-foreground">{label}</p><strong className="text-lg font-semibold">{value}</strong></div>; }
